version: '3.8'

services:
  app:
    build: .
    container_name: rentzone-app
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
    networks:
      - rentzone-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  rentzone-network:
    driver: bridge
