version: '3.8'

services:
  app:
    build: .
    container_name: travel-and-tours-app
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
    networks:
      - travel-and-tours-app-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  travel-and-tours-app-network:
    driver: bridge
